import "../(frontend)/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="Sqic4jq1KYYPLx4_l5xWdFBG3ormalt-u2eAb3BdSak"
        />
      </head>
      <body className="antialiased">
        <main style={{ flex: "1 0 auto" }}>{children}</main>
      </body>
    </html>
  );
}
