import AdminDashboardLayout from '../components/AdminDashboardLayout';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default async function RootLayout({ children }) {


  return (
          <AdminDashboardLayout>
              {children}        
          </AdminDashboardLayout>
  );
}