import "./globals.scss";
import Header from "./component/partials/Header";
import Footer from "./component/partials/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        <main style={{ flex: '1 0 auto' }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
