import "./globals.scss";
import Header from "./component/partials/Header";
import Footer from "./component/partials/Footer";
import Script from 'next/script'; // Import the Script component

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="suKFSXDWpXvnLlBzj_osoCgWVYGJEGilsS9xndMUs3I" />
      </head>
      <body className="antialiased">
        {/* Google Tag Manager noscript fallback */}
        <noscript
          dangerouslySetInnerHTML={{
            __html: `
              <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M99JNB3H"
              height="0" width="0" style="display:none;visibility:hidden"></iframe>
            `,
          }}
        />
        
        <Header />
        <main style={{ flex: '1 0 auto' }} >{children}</main>
        <Footer />
        
        {/* Google Tag Manager script using next/script */}
        <Script
          id="gtm-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-M99JNB3H');
            `,
          }}
        />
      </body>
    </html>
  );
}